spring:
 application.name: xyz-gateway-service
 # Set the following property to "none" or "validate" in a prod environment
 jpa:
  hibernate:
   ddl-auto: validate
  
  properties: 
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    boot.allow_jdbc_metadata_access: false
    
 flyway:
  enabled: false
  
   
 datasource:
  url: jdbc:mysql://localhost:3307/xyz_unversity
  username: david
  password: david123
  # Wait for 60 seconds during startup to establish db connection
  hikari.initializationFailTimeout: 60000
 
server:
 port: 7003
 error.include-message: always
 

logging:
 level:
  root: INFO
  com.david.microservices.alpha: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  

api:
 common:
  title: Student Service API
  description: This is a Student Service API that is used to handle student validations and handle payment notifications
  version: 1.0.0
  
  termsOfService: https://david-matu.github.io/alpha-microservices/terms-of-service
  license: General Usage License
  licenseUrl: https://david-matu.github.io/alpha-microservices/license
  
  externalDocDesc: Find out the public info about this API
  externalDocUrl: https://david-matu.github.io/alpha-microservices
  
  contact:
   name: David Matu
   url: https://david-matu.github.io
   email: davidmatu817@gmail.com
   
 responseCodes:
  ok.description: OK
  badRequest.description: Bad Request, invalid format of the request. See response message for more information 
  notFound.description: Not found. The specified id does not exist 
  unprocessableEntity.description: Uprocessable entity, input parameters caused the processing to fail. See response message for more information
 
 enrolment:
  get-student:
   summary: Get a Student record by passing ID
   description: |
    # Normal response
    200 - OK - When a Student is returned, it indicates payment can be made for them since they are active
    
    200 - OK - but empty object
    This is the case when the StudentID does not reflect a particular Student record, or the Student is no longer marked _ACTIVE_ in the institution
  
  add-student:
   summary: Add new Student
   description: Create Student profile in the database
   
  get-student-all:
   summary: Fetch all Students
   description: Returns a list of all students available,  and who are capable of being identified with payments made for
   
springdoc:
 swagger-ui.path: /openapi/swagger-ui.html
 api-docs.path: /openapi/v3/api-docs
 packagesToScan: edu.xyz.services.gateway
 pathsToMatch: /**
 
spring.cloud.stream:
 defaultBinder: rabbit
 default.contentType: application/json
 bindings:
  students-out-0:
   destination: studentq
   producer:
    required-groups: studentAuditGroup
  
spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  
app:
 student-service:
  host: xyz-enrolment-service
  port: 8080
  
---
spring:
 config.activate.on-profile: docker
  
spring.rabbitmq.host: rabbitmq

server.port: 8080

app:
 student-service:
  host: xyz-enrolment-service
  port: 8080

---
spring.config.activate.on-profile: streaming_partitioned

spring.cloud.stream.bindings.students-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 1

---
spring.config.activate.on-profile: kafka

management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
spring.cloud.stream.kafka.binder.replication-factor: 1